#!/bin/sh
set -e

# Only copy Carthage binaries to BUILT_PRODUCTS_DIR when not in developer mode.
# (when frameworks are not built from sources in platform/apple/GoldenGate.xcworkspace)
if [[ ! -L "Carthage/Dev" ]]; then

    [[ ${PLATFORM_NAME} == iphone* ]] \
        && FRAMEWORKS_DIR=Carthage/Build/iOS \
        || FRAMEWORKS_DIR=Carthage/Build/Mac

    echo "Copying Carthage binaries from ${FRAMEWORKS_DIR} to ${BUILT_PRODUCTS_DIR}..."
    rsync --delete -av "${FRAMEWORKS_DIR}/"*.framework* "${BUILT_PRODUCTS_DIR}"

    if which carthage >/dev/null
    then
        external/workflows/carthage-verify
    fi
fi
