# Enable/disable groups
set(GG_ENABLE_APPS FALSE CACHE BOOL "")
set(GG_ENABLE_EXAMPLES FALSE CACHE BOOL "")
set(GG_ENABLE_UNIT_TESTS FALSE CACHE BOOL "")

# Shared configuation options
set(GG_CONFIG_ENABLE_ANNOTATIONS FALSE CACHE BOOL "")
set(GG_CONFIG_ENABLE_LOGGING TRUE CACHE BOOL "")
set(GG_CONFIG_ENABLE_THREAD_GUARDS TRUE CACHE BOOL "")
#set(GG_CONFIG_DEFAULT_SOCKETS_MODULE "Lwip" CACHE STRING "")
set(GG_CONFIG_DEFAULT_SOCKETS_MODULE "Nip" CACHE STRING "")

# Ports selection
set(GG_PORTS_ENABLE_GENERIC_LOOP TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_MBEDTLS FALSE CACHE BOOL "")
set(GG_PORTS_ENABLE_MBEDTLS_TLS TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_STDC_CONSOLE TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_STDC_RANDOM TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_NULL_ENVIRONMENT TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_NULL_LOG_CONFIG TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_STDC_CONSOLE TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_FREERTOS_TIME TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_FREERTOS_THREADS TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_FREERTOS_SHARED_QUEUE TRUE CACHE BOOL "")
#set(GG_PORTS_ENABLE_LWIP_NETCONN_SOCKETS TRUE CACHE BOOL "")
#set(GG_PORTS_ENABLE_LWIP_NETIF TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_NIP TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_NIP_NETIF TRUE CACHE BOOL "")
set(GG_PORTS_ENABLE_NIP_SOCKETS TRUE CACHE BOOL "")
