// Copyright 2017-2020 Fitbit, Inc
// SPDX-License-Identifier: Apache-2.0

// Just here to silence empty-translation-unit warning.
// Since the output generated by this file is overwritten,
// the symbol `zero` won't pollute symbol space.
extern int zero;
int zero = 0;
