# Copyright 2017-2020 Fitbit, Inc
# SPDX-License-Identifier: Apache-2.0

include(${CMAKE_CURRENT_LIST_DIR}/pylon.cmake)

set(GG_CONFIG_ENABLE_ANNOTATIONS FALSE CACHE BOOL "")
set(GG_CONFIG_LOGGING_MIN_LEVEL "GG_LOG_LEVEL_INFO" CACHE STRING "")
